apiVersion: v1
kind: Pod
metadata:
  name: restapi-test
  namespace: agc2022-test
spec:
  containers:
  - name: restapi-test
    image: 10.0.0.255:5000/agc2022_test/restapi_test:1.0
    env:
    - name: REST_URL
      value: 10.0.7.1